apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-example-role
rules:
  - verbs: ["get"]
    apiGroups: [""]
    resources: ["configmaps", "secrets"]
#    resourceNames: ["k8s-example-cm"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-example-rb
roleRef:
  kind: Role
  name: k8s-example-role
  apiGroup: "rbac.authorization.k8s.io"
subjects:
  - kind: ServiceAccount
    name: k8s-example-sa